baseURL: https://academic-folio.netlify.app
languageCode: en
title: Academic Folio
copyright: © Copyright 2023 The Academic Folio Contributors

enableEmoji: true

enableRobotsTXT: true

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
