[build]
command = "hugo -s exampleSite --minify -b $URL"
publish = "exampleSite/public"

[build.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "hugo -s exampleSite --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo -s exampleSite --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_ENV = "production"
