baseURL: https://academic-folio.netlify.app
languageCode: en
title: Academic Folio
copyright: > 
          &copy; Copyright 2023 The Academic Folio Contributors &bull;
          Powered by <a href="https://gohugo.io">Hugo</a> with
          <a href="https://github.com/rohandebsarkar/academic-folio">Academic Folio</a> theme

theme: academic-folio

enableEmoji: true

enableRobotsTXT: true

markup:
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
